http:
  port: 8080


zap:
  level: debug
  format: console
  prefix: "my-ops-admin"
  director: logs
  show-line: true
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1
  log-in-file: false
  log-file-name: "app.log"