http:
  port: 8080

postgresql:
  host: "192.168.50.37"
  port: 5432
  username: "mypg"
  password: "Make@2025"
  dbname: "mypg"
  schema: "mypg"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

zap:
  level: debug
  format: console
  prefix: "my-ops-admin"
  director: logs
  show-line: true
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1
  log-in-file: false
  log-file-name: "app.log"